sudo: required
dist: precise
language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - boost-latest
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - libboost1.55-all-dev
      env: COMPILER=g++-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - boost-latest
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - libboost1.55-all-dev
      env: COMPILER=g++-5
 


before_install:
- sudo apt-get update -qq
- pip install --user cpp-coveralls

install:
  - ./travis-tool.sh github_package jimhester/covr
 
script:
- mkdir build
- cd build
- cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && make
- ctest


after_success:
- coveralls --gcov-options '\-lp'

