sudo: required
dist: precise
language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - libboost1.55-all-dev
      env: COMPILER=g++-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - libboost1.55-all-dev
      env: COMPILER=g++-5
      

before_install:
- sudo apt-get update -qq


script:
- mkdir build
- cd build
- cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && make
- echo Oh yes I did ...
- ctest

