sudo: required
dist: precise
language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - boost-latest
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - libboost1.55-all-dev
      env: COMPILER=g++-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - boost-latest
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - libboost1.55-all-dev
      env: COMPILER=g++-5
 


before_install:
- sudo apt-get update -qq
- sudo apt-get install lcov rubygems
- gem install lcoveralls

 
script:
- mkdir build
- cd build
- cmake -DCMAKE_CXX_COMPILER=$COMPILER -DWITHTESTS:BOOL=ON  -DWITHEXAMPLES:BOOL=ON -DWITHCOVERAGE:BOOL=ON .. 
- make
- ctest
- lcov -b . -d . --capture


after_success:
- lcoveralls

